apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dept-spring
  namespace: argocd
  resourceVersion: "1431242"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/dept-spring
  uid: 6fe153c5-1a26-48a0-b67f-d43062f8bbed
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: /
    repoURL: https://github.com/htdp1/argocd-apps.git
    targetRevision: HEAD